dataset:
    frames_per_clip: 10
    step_between_clips: 10
    batch_size: 32
    transform:
        Normalize:
            mean: 0.449
            std: 0.226
        HorizontalFlip: True
        Cutout: False
    transformOF:
        Normalize: ~
        HorizontalFlip: True
        Cutout: False

model:
    phase1:
        epochs: 10
        lr: 0.005
        step_size: 5
        gamma: 0.5
    phase2:
        epochs: 45
        lr: 0.00002
        step_size: 15
        gamma: 0.5
        